language: ruby
rvm:
  - 2.3.1
services:
    - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - psql -U postgres -c "create extension postgis" -d travis_ci_test
    - rake db:migrate
