language: ruby
rvm:
  - 2.3.1
services:
    - postgresql
# before_script:
#     - psql -c 'create database travis_ci_test;' -U postgres
#     - psql -c 'create user moacir;' -U postgres
#     - psql travis_ci_test < db/schema.dmp
