dist: trusty
sudo: required
language: ruby
rvm:
  - 2.3.1
# https://gis.stackexchange.com/questions/252609/could-not-access-file-libdir-postgis-2-3-on-travis-installation
# https://github.com/travis-ci/travis-ci/issues/6972
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-9.6-postgis-2.4
  - psql -U postgres -c 'create database travis_ci_test'
  - psql -U postgres -d travis_ci_test -c 'create extension postgis'
  - psql -c 'create user moacir;' -U postgres
  - psql travis_ci_test < db/schema.dmp
